### ISSUE TITLE
Mozarella size is not configurable in Terminal

### ISSUE THREAD

**Issue by HKanwal** [jere-mie/tiny-web#1]
Upon using the `mozarella` command in the Terminal project, client should be able to customize the size.

Proposed solutions:
- Allow client to enter dimensions as arguments to the command. For example `mozarella <height> <width>`
- Allow client to enter scale as a single argument, keeping the original image ratio. For example `mozarella 1.5`

Future feature recommendations:
- Make the mozarella 3-dimensional
- Display a random mozarella gif from a assortment of various gifs for variety

I think these features are essential for the user experience. Other similar services provide variable mozarella out of the box.

**Comment by jere-mie** [comment]
added :)
